# Força o Python a liberar memória pro sistema imediatamente
export PYTHONMALLOC=malloc

# Desativa avisos e logs pesados de desenvolvimento do Python
export PYTHONDEVMODE=0

# Limita o GN a usar menos threads na geração para não estourar a RAM
export GN_ARGS="concurrent_links=2"
