# Flags Compiller
#COMMON_FLAGS="-march=native -O2 -pipe -fomit-frame-pointer -fstack-protector-strong -flto=auto"
COMMON_FLAGS="-march=native -O2 -pipe -fstack-protector-all -flto=auto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
#LDFLAGS="-Wl,-O1 -Wl,--as-needed -flto=auto"
#LDFLAGS="-Wl,-O1 -Wl,--as-needed -fuse-ld=lld"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -flto=auto"
#RUSTFLAGS="-C target-cpu=native -C opt-level=3"
RUSTFLAGS="-C target-cpu=native -C opt-level=2 -C link-arg=-Wl,-z,relro -C link-arg=-Wl,-z,now"

#egl gbm sound-server handbook acpi pgo"
USE="X wayland abi_x86_64 bluetooth input_devices_libinput ipv6 ipv4 kde l10n_pt-BR linguas_pt_BR networkmanager office_implementation_libreoffice pipewire -plasma qt6 systemd video_cards_intel video_cards_nvidia vulkan -dvd -dvdr -cdr -elogin -openrc gtk -gnome alsa opengl pgo gbm egl gpm jpeg"
#USE="X wayland abi_x86_64 bluetooth input_devices_libinput ipv6 ipv4 -kde -qt6 l10n_pt-BR linguas_pt_BR networkmanager office_implementation_libreoffice pipewire -plasma -qt6 systemd video_cards_intel video_cards_nvidia vulkan -dvd -dvdr -cdr -elogind -openrc gtk -gnome alsa opengl pgo gbm egl gpm jpeg hardened pic"
EMERGE_DEFAULT_OPTS="--autounmask-write=y"
# --jobs=4 --load-average=6"
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"
MAKEOPTS="-j10 -l9"
NINJAOPTS="${MAKEOPTS}"

L10N="pt-BR"
LINGUAS="pt_BR"
INPUT_DEVICES="libinput"
OFFICE_IMPLEMENTATION="libreoffice"
VIDEO_CARDS="intel nvidia"
ABI_X86="64"
GRUB_PLATFORMS="efi-64"

FEATURES="buildpkg parallel-fetch parallel-install"
BINPKG_COMPRESS="zstd"
BINPKG_COMPRESS_FLAGS="-19"
PORTAGE_ELOG_SYSTEM="save"

PORTAGE_NICENESS="0"
PORTAGE_IONICE_COMMAND="ionice -c 2 -n 0 -p \${PID}"
# scheduler padrão (normal), não idle
PORTAGE_SCHEDULING_POLICY="other"


LC_MESSAGES=pt_BR.UTF-8

GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/ \
    https://br.mirrors.cicku.me/gentoo/ \
    https://us.mirrors.cicku.me/gentoo/"
