# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe -fno-lto"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
#LDFLAGS="-Wl,-O1 -Wl,--as-needed -flto"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -fno-lto"
RUSTFLAGS="-C target-cpu=native -C opt-level=3"

USE="X cuda modemmanager qt5 wayland qt6 -lto -gnome systemd kde pipewire gtk -dvd -cdr -openrc -elogind policykit alsa bluetooth networkmanager opengl vulkan egl gbm sound-server kde plasma handbook acpi -pgo"
EMERGE_DEFAULT_OPTS="--autounmask-write=y --verbose --load-average=6"
ACCEPT_LICENSE="*"

ACCEPT_KEYWORDS="~amd64"
MAKEOPTS="-j6 -l6"
NINJAOPTS="${MAKEOPTS}"

INPUT_DEVICES="libinput"
OFFICE_IMPLEMENTATION="libreoffice"
VIDEO_CARDS="intel nvidia"
LINGUAS="pt_BR en_US"
L10N="pt-BR en-US"


ABI_X86="64 32"
GRUB_PLATFORMS="efi-64"

FEATURES="buildpkg parallel-fetch parallel-install"
BINPKG_COMPRESS="zstd"
BINPKG_COMPRESS_FLAGS="-19"
PORTAGE_ELOG_SYSTEM="save"

PORTAGE_NICENESS="0"
PORTAGE_IONICE_COMMAND="ionice -c 2 -n 0 -p \${PID}"
# scheduler padrão (normal), não idle
PORTAGE_SCHEDULING_POLICY="other"


# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/ \
    https://br.mirrors.cicku.me/gentoo/ \
    https://umbriel.br.ext.planetunix.net/pub/gentoo/ \
    https://ca.mirrors.cicku.me/gentoo/ \
    https://jp.mirrors.cicku.me/gentoo/ \
    https://ftp.lysator.liu.se/gentoo/ \
    https://gb.mirrors.cicku.me/gentoo/ \
    https://us.mirrors.cicku.me/gentoo/ \
    http://us.mirrors.cicku.me/gentoo/"
