# created by eselect-repo




[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git



[cosmic-overlay]
location = /var/db/repos/cosmic-overlay
sync-type = git
sync-uri = https://github.com/fsvm88/cosmic-overlay.git

[tatsh-overlay]
location = /var/db/repos/tatsh-overlay
sync-type = git
sync-uri = https://github.com/Tatsh/tatsh-overlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[pentoo]
location = /var/db/repos/pentoo
sync-type = git
sync-uri = https://github.com/pentoo/pentoo-overlay.git
