# created by eselect-repo

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[r7l]
location = /var/db/repos/r7l
sync-type = git
sync-uri = https://github.com/r7l/r7l-overlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git


[pf4public]
location = /var/db/repos/pf4public
sync-type = git
sync-uri = https://github.com/PF4Public/gentoo-overlay.git



[tatsh-overlay]
location = /var/db/repos/tatsh-overlay
sync-type = git
sync-uri = https://github.com/Tatsh/tatsh-overlay.git


